Juntando repositórios para poder trabalhar em um só
guidytz/SUMO-QL pull request #8
Opened 2022-10-19 00:24 UTC by hugobbi

2022-10-19 12:08 UTC, guidytz requested changes
Adicionei pequenas alterações que precisam ser feitas.

2022-10-19 12:08 UTC, guidytz commented on sumo_ql/environment/communication_device.py
> +            reward (list): Reward values to insert in link queue
```suggestion
            reward (np.ndarray): Reward values to insert in link queue
```

2022-10-19 12:08 UTC, guidytz commented on sumo_ql/environment/communication_device.py
> +            list: List of averages of the stored rewards for the given link if there is data stored or 0.0 otherwise
```suggestion
            np.ndarray: List of averages of the stored rewards for the given link if there is data stored or 0.0 otherwise
```

2022-10-19 12:08 UTC, guidytz commented on sumo_ql/environment/communication_device.py
> +    # modificar para que, para cada link de saída, programa busca vizinhos no grafo no tempo atual da simulação e envia os dados
Aqui seria um "to do" ou já foi feito?
```suggestion
    #TODO: modificar para que, para cada link de saída, programa busca vizinhos no grafo no tempo atual da simulação e envia os dados
```

2022-10-19 12:08 UTC, guidytz commented on testes.py
> +    print (":(")
Esse arquivo é necessário?

2022-10-19 12:08 UTC, guidytz commented on tt.py
> +print(str(a))
Creio que esse arquivo possa ser excluído também

2022-10-19 12:08 UTC, guidytz commented on utilities/aggregateCsvByStep.py
> +		print('aggr_'+fname_save+'.csv created in current directory')
Seria bom alterar o nome do arquivo para ficar em snake case e manter a convenção da linguagem. Assim: aggregate_csv_by_step.py

2022-10-19 15:58 UTC, hugobbi commented on comando.txt
> +python3 simulations/sumo_run.py -f sumo_graphs/data/teste.csv -atb 3 -rdata -lim 0.01 -id 2 1 -c scenario/diamond/diamond.sumocfg -s 10000 --collect -r 1 -m 250 --objectives TravelTime CO -a PQL
Com certeza, eu achei que tinha removido esses arquivos, eles não são necessários. Esse servia apenas para eu ter o comando salvo para fazer os testes em vez de ter que reescrevê-lo

2022-10-19 15:59 UTC, hugobbi commented on anotacoes.txt
> +malloc_consolidate(): unaligned fastbin chunk detected
Sim, pode ser excluído, era apenas anotações minhas de desenvolvimento, achei que tinha removido :/

2022-10-19 16:01 UTC, hugobbi commented on sumo_ql/environment/communication_device.py
> +    # modificar para que, para cada link de saída, programa busca vizinhos no grafo no tempo atual da simulação e envia os dados
Já foi feito, eu tinha anotado o que deveria fazer para lembrar depois, mas acabei esquecendo de remover essa anotação

2022-10-19 16:02 UTC, hugobbi commented on testes.py
> +    print (":(")
Não, ele servia apenas para testar algumas partes diversas específicas, achei que tinha removido

2022-10-19 16:03 UTC, hugobbi commented on tt.py
> +print(str(a))
Também pode ser excluído, serve apenas para testes específicos. Pensei que eu tivesse removido esses arquivos e colocado no .gitignore, mas pelo visto não foi removido de fato

2022-10-19 16:03 UTC, hugobbi commented on utilities/aggregateCsvByStep.py
> +		print('aggr_'+fname_save+'.csv created in current directory')
Certo

2022-10-19 16:19 UTC, hugobbi commented on sumo_ql/environment/communication_device.py
> +    # modificar para que, para cada link de saída, programa busca vizinhos no grafo no tempo atual da simulação e envia os dados
Criei um commit para remover esse comentário

2022-10-19 16:34 UTC, hugobbi commented
Eu removi os arquivos desnecessários que não eram para estar no commit final que você comentou e também mais alguns outros que eu adicionei que também não precisavam estar ali. Ainda há dois arquivos meus que não consegui deletar pelo commit, pois, pelo que diz, não pertencem à branch, mas sim a outro fork. Esses arquivos estão em pastas em sumo_graphs/data, e são referentes a dados de entrada para montar o grafo virtual

2022-10-19 16:45 UTC, hugobbi reviewed
Eu removi os arquivos desnecessários que não eram para estar no commit final que você comentou e também mais alguns outros que eu adicionei que também não precisavam estar ali. Ainda há dois arquivos meus que não consegui deletar pelo commit, pois, pelo que diz, não pertencem à branch, mas sim a outro fork. Esses arquivos estão em pastas em sumo_graphs/data, e são referentes a dados de entrada para montar o grafo virtual

2022-10-20 00:33 UTC, guidytz approved these changes

2022-10-20 00:34 UTC, merged